### ISSUE TITLE
Ingesting NFT metadata for assembly

### ISSUE THREAD

**Issue by madjin** [gm3/boom-tools#28]
This is for use-case when you are configuring boom-tools to assemble 1:1 3D files for an already generated NFT collection
- load up metadata
- batch export files
- ????
- PROFIT

![](https://i.imgur.com/WzMaSBv.png)
https://ipfs.io/ipfs/QmfU2q6NGGCY7C5c2ncM8UJ6q9j6KqyHA4uiZCRPrXvV3U/
https://github.com/M3-org/tubby-pet/blob/main/tubbycats_metadata.json

**Comment by gm3** [comment]
This is tested and ive been able to load the JSON and the assets, need to scale test
