### ISSUE TITLE
Weird comma placement in JSON export

### ISSUE THREAD

**Issue by madjin** [gm3/boom-tools#29]
how it looks
![image](https://user-images.githubusercontent.com/32600939/186021987-0efab6b1-9f7a-48b2-8d92-e520ed266c50.png)

how normal JSON looks
![image](https://user-images.githubusercontent.com/32600939/186022028-422a4166-727b-4dfe-9685-ab9531300c05.png)

**Comment by gm3** [comment]
fixed
